# Copyright (c) 2026, RTE (https://www.rte-france.com)
# See AUTHORS.txt
# This Source Code Form is subject to the terms of the Mozilla Public License, version 2.0.
# If a copy of the Mozilla Public License, version 2.0 was not distributed with this file,
# you can obtain one at http://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
# This file is part of LightSim2grid, LightSim2grid implements a c++ backend targeting the Grid2Op platform.

"""AUTO-GENERATED by lightsim2grid/tests/_gen_exotic_elements_case.py -- DO NOT EDIT BY HAND.

Reproduces the grid built by `_exotic_elements_fixture.build_exotic_elements_grid()` (IEEE14 +
SVC + storage + 3 HVDC lines + a phase-shifting transformer) via literal `LSGrid.init_*`/
`add_*`/`set_*` calls captured from a real `init_from_pypowsybl` run -- no pypowsybl/
pandapower/grid2op dependency at runtime, only numpy + lightsim2grid.

Generated on 2026-07-16 using `python -m lightsim2grid.tests._gen_exotic_elements_case` (lightsim2grid 1.0.0.rc2, pypowsybl 1.15.0).
"""

import numpy as np

from lightsim2grid.network import LSGrid


def build_exotic_elements_case_grid() -> LSGrid:
    """Unsolved: callers run their own ac_pf / dc_pf, same contract as
    `_exotic_elements_fixture.build_exotic_elements_grid(solve=False)`."""
    model = LSGrid()

    model.set_sn_mva(
        100.0
    )
    model.set_init_vm_pu(
        1.06
    )
    model.init_bus(
        14,
        1,
        np.array([135.0, 12.0, 12.0, 12.0, 12.0, 12.0, 135.0, 135.0, 135.0, 135.0, 12.0, 14.0, 20.0, 12.0], dtype=np.float64),
        0,
        0
    )
    model.init_generators_full(
        np.array([232.4, 40.0, 0.0, 0.0, 0.0], dtype=np.float64),
        np.array([1.06, 1.045, 1.01, 1.07, 1.09], dtype=np.float64),
        np.array([-16.9, 42.4, 23.4, 12.2, 17.4], dtype=np.float64),
        [True, True, True, True, True],
        np.array([-3.4028233356588204e+34, -40.0, 0.0, -6.0, -6.0], dtype=np.float32),
        np.array([3.4028233356588204e+34, 50.0, 40.0, 24.0, 24.0], dtype=np.float32),
        np.array([0, 6, 7, 10, 12], dtype=np.int64)
    )
    model.init_loads(
        np.array([9.0, 3.5, 6.1, 13.5, 14.9, 21.7, 94.2, 47.8, 7.6, 11.2, 29.5], dtype=np.float64),
        np.array([5.8, 1.8, 1.6, 5.8, 5.0, 12.7, 19.0, -3.9, 1.6, 7.5, 16.6], dtype=np.float64),
        np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13], dtype=np.int64)
    )
    model.init_powerlines_full(
        np.array([0.01938, 0.054029999999999995, 0.08205, 0.22091999999999998, 0.17093, 0.04698999999999999, 0.058109999999999995, 0.05694999999999999, 0.06701, 0.01335, 0.09497999999999998, 0.12290999999999999, 0.06615, 0.0, 0.0, 0.03180999999999999, 0.12711], dtype=np.float64),
        np.array([0.05916999999999999, 0.22304, 0.19206999999999996, 0.19987999999999995, 0.34801999999999994, 0.19797, 0.17632, 0.17388, 0.17102999999999996, 0.042109999999999995, 0.1989, 0.25581, 0.13026999999999997, 0.17615000000000003, 0.11001, 0.08449999999999999, 0.27038], dtype=np.float64),
        np.array([complex(0.0, 0.0264), complex(0.0, 0.0246), complex(0.0, 0.0), complex(0.0, 0.0), complex(0.0, 0.0), complex(0.0, 0.0219), complex(0.0, 0.017), complex(0.0, 0.0173), complex(0.0, 0.0064), complex(0.0, 0.0), complex(0.0, 0.0), complex(0.0, 0.0), complex(0.0, 0.0), complex(0.0, 0.0), complex(0.0, 5.684341886080802e-16), complex(0.0, 0.0), complex(0.0, 0.0)], dtype=np.complex128),
        np.array([complex(0.0, 0.0264), complex(0.0, 0.0246), complex(0.0, 0.0), complex(0.0, 0.0), complex(0.0, 0.0), complex(0.0, 0.0219), complex(0.0, 0.017), complex(0.0, 0.0173), complex(0.0, 0.0064), complex(0.0, 0.0), complex(0.0, 0.0), complex(0.0, 0.0), complex(0.0, 0.0), complex(0.0, 2.842170943040401e-16), complex(0.0, -5.684341886080802e-16), complex(0.0, 0.0), complex(0.0, 0.0)], dtype=np.complex128),
        np.array([0, 0, 1, 3, 4, 6, 6, 6, 7, 8, 10, 10, 10, 11, 11, 13, 13], dtype=np.int64),
        np.array([6, 9, 2, 4, 5, 7, 8, 9, 8, 9, 2, 3, 4, 12, 13, 1, 5], dtype=np.int64)
    )
    model.init_trafo(
        np.array([0.0, 0.0, 0.0], dtype=np.float64),
        np.array([0.20912, 0.55618, 0.25202], dtype=np.float64),
        np.array([complex(0.0, 0.0), complex(0.0, 0.0), complex(0.0, 0.0)], dtype=np.complex128),
        np.array([1.0224948875255624, 1.0319917440660473, 1.0729613733905579], dtype=np.float64),
        np.array([0.0, 0.0, 0.0], dtype=np.float64),
        [False, False, False],
        np.array([8, 8, 9], dtype=np.int64),
        np.array([11, 13, 10], dtype=np.int64),
        False
    )
    model.set_trafo_shift_dependent_rx(
        True,
        [[-0.08726646259971647, 0.0, 0.08726646259971647], [], []],
        [[0.0, 0.0, 0.0], [], []]
    )
    model.init_shunt(
        np.array([0.0], dtype=np.float64),
        np.array([-19.0], dtype=np.float64),
        np.array([13], dtype=np.int64)
    )
    model.init_svcs(
        [1],
        np.array([1.0], dtype=np.float64),
        np.array([-0.0], dtype=np.float64),
        np.array([0.08333333333333333], dtype=np.float64),
        np.array([-0.0288], dtype=np.float64),
        np.array([0.0288], dtype=np.float64),
        np.array([5], dtype=np.int32),
        np.array([5], dtype=np.int32)
    )
    model.init_hvdc_lines(
        np.array([5, 1, 3], dtype=np.int32),
        np.array([4, 2, 13], dtype=np.int32),
        [1, 0, 0],
        [1, 0, 0],
        np.array([0.01100000023841858, 0.01100000023841858, 0.01100000023841858], dtype=np.float64),
        np.array([0.01100000023841858, 0.01100000023841858, 0.01100000023841858], dtype=np.float64),
        [False, True, True],
        [False, True, True],
        np.array([1.0, 1.0, 1.0], dtype=np.float64),
        np.array([1.0, 1.0, 1.0], dtype=np.float64),
        np.array([0.0, 0.0, 0.0], dtype=np.float64),
        np.array([0.0, 0.0, 0.0], dtype=np.float64),
        np.array([-10000000.0, -1.7976931348623157e+308, -1.7976931348623157e+308], dtype=np.float64),
        np.array([10000000.0, 1.7976931348623157e+308, 1.7976931348623157e+308], dtype=np.float64),
        np.array([-10000000.0, -1.7976931348623157e+308, -1.7976931348623157e+308], dtype=np.float64),
        np.array([10000000.0, 1.7976931348623157e+308, 1.7976931348623157e+308], dtype=np.float64),
        np.array([0.8999999761581421, 1.0, 1.0], dtype=np.float64),
        np.array([0.8999999761581421, 1.0, 1.0], dtype=np.float64),
        [0, 0, 0],
        np.array([1.0, 2.0, 2.0], dtype=np.float64),
        np.array([1.0, 1.0, 1.0], dtype=np.float64),
        np.array([12.0, 12.0, 12.0], dtype=np.float64),
        [False, True, False],
        np.array([0.0, 1.0, 0.0], dtype=np.float64),
        np.array([0.0, 180.0, 0.0], dtype=np.float64),
        np.array([20.0, 20.0, 20.0], dtype=np.float64),
        np.array([20.0, 20.0, 20.0], dtype=np.float64)
    )
    model.init_storages(
        np.array([-5.0], dtype=np.float64),
        np.array([-1.0], dtype=np.float64),
        np.array([4], dtype=np.int64)
    )
    model.add_gen_slackbus(
        0,
        1.0
    )
    model.consider_only_main_component()

    return model
