// Copyright (c) 2026, RTE (https://www.rte-france.com)
// See AUTHORS.txt
// This Source Code Form is subject to the terms of the Mozilla Public License, version 2.0.
// If a copy of the Mozilla Public License, version 2.0 was not distributed with this file,
// you can obtain one at http://mozilla.org/MPL/2.0/.
// SPDX-License-Identifier: MPL-2.0
// This file is part of LightSim2grid, LightSim2grid implements a c++ backend targeting the Grid2Op platform.

#ifndef LS2G_CASE_EXOTIC_ELEMENTS_H
#define LS2G_CASE_EXOTIC_ELEMENTS_H

// AUTO-GENERATED by lightsim2grid/tests/_gen_exotic_elements_case.py -- DO NOT EDIT BY HAND.
//
// Reproduces the grid built by lightsim2grid.tests._exotic_elements_fixture.
// build_exotic_elements_grid() (IEEE14 + SVC + storage + 3 HVDC lines + a phase-shifting
// transformer) via literal LSGrid init_*/add_*/set_* calls captured from a real
// init_from_pypowsybl run -- no pypowsybl/pandapower/grid2op dependency, pure C++.
//
// Generated on 2026-07-16 using `python -m lightsim2grid.tests._gen_exotic_elements_case` (lightsim2grid 1.0.0.rc2, pypowsybl 1.15.0).

#include <complex>
#include <vector>

#include "LSGrid.hpp"

namespace ls2g_test {

inline ls2g::LSGrid make_exotic_elements_grid()
{
    using ls2g::LSGrid;
    using ls2g::RealVect;
    using ls2g::CplxVect;
    using ls2g::real_type;

    LSGrid grid;

    grid.set_sn_mva(100.0);

    grid.set_init_vm_pu(1.06);

    RealVect bus_vn_kv(14);
    bus_vn_kv << 135.0, 12.0, 12.0, 12.0, 12.0, 12.0, 135.0, 135.0, 135.0, 135.0, 12.0, 14.0, 20.0, 12.0;
    grid.init_bus(14, 1, bus_vn_kv, 0, 0);

    RealVect gen_p(5);
    gen_p << 232.4, 40.0, 0.0, 0.0, 0.0;
    RealVect gen_v_pu(5);
    gen_v_pu << 1.06, 1.045, 1.01, 1.07, 1.09;
    RealVect gen_q(5);
    gen_q << -16.9, 42.4, 23.4, 12.2, 17.4;
    const std::vector<bool> gen_voltage_regulator_on{true, true, true, true, true};
    RealVect gen_min_q(5);
    gen_min_q << -3.4028233356588204e+34, -40.0, 0.0, -6.0, -6.0;
    RealVect gen_max_q(5);
    gen_max_q << 3.4028233356588204e+34, 50.0, 40.0, 24.0, 24.0;
    Eigen::VectorXi gen_bus_id(5);
    gen_bus_id << 0, 6, 7, 10, 12;
    grid.init_generators_full(gen_p, gen_v_pu, gen_q, gen_voltage_regulator_on, gen_min_q, gen_max_q, gen_bus_id);

    RealVect load_p(11);
    load_p << 9.0, 3.5, 6.1, 13.5, 14.9, 21.7, 94.2, 47.8, 7.6, 11.2, 29.5;
    RealVect load_q(11);
    load_q << 5.8, 1.8, 1.6, 5.8, 5.0, 12.7, 19.0, -3.9, 1.6, 7.5, 16.6;
    Eigen::VectorXi load_bus_id(11);
    load_bus_id << 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13;
    grid.init_loads(load_p, load_q, load_bus_id);

    RealVect line_r(17);
    line_r << 0.01938, 0.054029999999999995, 0.08205, 0.22091999999999998, 0.17093, 0.04698999999999999, 0.058109999999999995, 0.05694999999999999, 0.06701, 0.01335, 0.09497999999999998, 0.12290999999999999, 0.06615, 0.0, 0.0, 0.03180999999999999, 0.12711;
    RealVect line_x(17);
    line_x << 0.05916999999999999, 0.22304, 0.19206999999999996, 0.19987999999999995, 0.34801999999999994, 0.19797, 0.17632, 0.17388, 0.17102999999999996, 0.042109999999999995, 0.1989, 0.25581, 0.13026999999999997, 0.17615000000000003, 0.11001, 0.08449999999999999, 0.27038;
    CplxVect line_h1(17);
    line_h1 << std::complex<double>(0.0, 0.0264), std::complex<double>(0.0, 0.0246), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0219), std::complex<double>(0.0, 0.017), std::complex<double>(0.0, 0.0173), std::complex<double>(0.0, 0.0064), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 5.684341886080802e-16), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0);
    CplxVect line_h2(17);
    line_h2 << std::complex<double>(0.0, 0.0264), std::complex<double>(0.0, 0.0246), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0219), std::complex<double>(0.0, 0.017), std::complex<double>(0.0, 0.0173), std::complex<double>(0.0, 0.0064), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 2.842170943040401e-16), std::complex<double>(0.0, -5.684341886080802e-16), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0);
    Eigen::VectorXi line_from_id(17);
    line_from_id << 0, 0, 1, 3, 4, 6, 6, 6, 7, 8, 10, 10, 10, 11, 11, 13, 13;
    Eigen::VectorXi line_to_id(17);
    line_to_id << 6, 9, 2, 4, 5, 7, 8, 9, 8, 9, 2, 3, 4, 12, 13, 1, 5;
    grid.init_powerlines_full(line_r, line_x, line_h1, line_h2, line_from_id, line_to_id);

    RealVect trafo_r(3);
    trafo_r << 0.0, 0.0, 0.0;
    RealVect trafo_x(3);
    trafo_x << 0.20912, 0.55618, 0.25202;
    CplxVect trafo_b(3);
    trafo_b << std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0), std::complex<double>(0.0, 0.0);
    RealVect trafo_ratio(3);
    trafo_ratio << 1.0224948875255624, 1.0319917440660473, 1.0729613733905579;
    RealVect trafo_shift_degree(3);
    trafo_shift_degree << 0.0, 0.0, 0.0;
    const std::vector<bool> trafo_tap_hv{false, false, false};
    Eigen::VectorXi trafo_bus1_id(3);
    trafo_bus1_id << 8, 8, 9;
    Eigen::VectorXi trafo_bus2_id(3);
    trafo_bus2_id << 11, 13, 10;
    grid.init_trafo(trafo_r, trafo_x, trafo_b, trafo_ratio, trafo_shift_degree, trafo_tap_hv, trafo_bus1_id, trafo_bus2_id, false);

    const std::vector<std::vector<real_type>> trafo_shift_alpha_rad = {
        {-0.08726646259971647, 0.0, 0.08726646259971647},
        {},
        {},
    };
    const std::vector<std::vector<real_type>> trafo_shift_rx_corr_pct = {
        {0.0, 0.0, 0.0},
        {},
        {},
    };
    grid.set_trafo_shift_dependent_rx(true, trafo_shift_alpha_rad, trafo_shift_rx_corr_pct);

    RealVect shunt_p_mw(1);
    shunt_p_mw << 0.0;
    RealVect shunt_q_mvar(1);
    shunt_q_mvar << -19.0;
    Eigen::VectorXi shunt_bus_id(1);
    shunt_bus_id << 13;
    grid.init_shunt(shunt_p_mw, shunt_q_mvar, shunt_bus_id);

    const std::vector<int> svc_regulation_mode{1};
    RealVect svc_target_vm_pu(1);
    svc_target_vm_pu << 1.0;
    RealVect svc_q_setpoint_mvar(1);
    svc_q_setpoint_mvar << -0.0;
    RealVect svc_slope_pu(1);
    svc_slope_pu << 0.08333333333333333;
    RealVect svc_b_min(1);
    svc_b_min << -0.0288;
    RealVect svc_b_max(1);
    svc_b_max << 0.0288;
    Eigen::VectorXi svc_regulated_bus_id(1);
    svc_regulated_bus_id << 5;
    Eigen::VectorXi svc_bus_id(1);
    svc_bus_id << 5;
    grid.init_svcs(svc_regulation_mode, svc_target_vm_pu, svc_q_setpoint_mvar, svc_slope_pu, svc_b_min, svc_b_max, svc_regulated_bus_id, svc_bus_id);

    Eigen::VectorXi hvdc_bus1_id(3);
    hvdc_bus1_id << 5, 1, 3;
    Eigen::VectorXi hvdc_bus2_id(3);
    hvdc_bus2_id << 4, 2, 13;
    const std::vector<int> hvdc_type1{1, 0, 0};
    const std::vector<int> hvdc_type2{1, 0, 0};
    RealVect hvdc_loss_factor1(3);
    hvdc_loss_factor1 << 0.01100000023841858, 0.01100000023841858, 0.01100000023841858;
    RealVect hvdc_loss_factor2(3);
    hvdc_loss_factor2 << 0.01100000023841858, 0.01100000023841858, 0.01100000023841858;
    const std::vector<bool> hvdc_vreg1_on{false, true, true};
    const std::vector<bool> hvdc_vreg2_on{false, true, true};
    RealVect hvdc_vm1_pu(3);
    hvdc_vm1_pu << 1.0, 1.0, 1.0;
    RealVect hvdc_vm2_pu(3);
    hvdc_vm2_pu << 1.0, 1.0, 1.0;
    RealVect hvdc_q1_setpoint_mvar(3);
    hvdc_q1_setpoint_mvar << 0.0, 0.0, 0.0;
    RealVect hvdc_q2_setpoint_mvar(3);
    hvdc_q2_setpoint_mvar << 0.0, 0.0, 0.0;
    RealVect hvdc_min_q1(3);
    hvdc_min_q1 << -10000000.0, -1.7976931348623157e+308, -1.7976931348623157e+308;
    RealVect hvdc_max_q1(3);
    hvdc_max_q1 << 10000000.0, 1.7976931348623157e+308, 1.7976931348623157e+308;
    RealVect hvdc_min_q2(3);
    hvdc_min_q2 << -10000000.0, -1.7976931348623157e+308, -1.7976931348623157e+308;
    RealVect hvdc_max_q2(3);
    hvdc_max_q2 << 10000000.0, 1.7976931348623157e+308, 1.7976931348623157e+308;
    RealVect hvdc_power_factor1(3);
    hvdc_power_factor1 << 0.8999999761581421, 1.0, 1.0;
    RealVect hvdc_power_factor2(3);
    hvdc_power_factor2 << 0.8999999761581421, 1.0, 1.0;
    const std::vector<int> hvdc_converters_mode{0, 0, 0};
    RealVect hvdc_p_setpoint_mw(3);
    hvdc_p_setpoint_mw << 1.0, 2.0, 2.0;
    RealVect hvdc_r_ohm(3);
    hvdc_r_ohm << 1.0, 1.0, 1.0;
    RealVect hvdc_nominal_v_kv(3);
    hvdc_nominal_v_kv << 12.0, 12.0, 12.0;
    const std::vector<bool> hvdc_droop_enabled{false, true, false};
    RealVect hvdc_droop_p0_mw(3);
    hvdc_droop_p0_mw << 0.0, 1.0, 0.0;
    RealVect hvdc_droop_mw_per_deg(3);
    hvdc_droop_mw_per_deg << 0.0, 180.0, 0.0;
    RealVect hvdc_pmax_1to2_mw(3);
    hvdc_pmax_1to2_mw << 20.0, 20.0, 20.0;
    RealVect hvdc_pmax_2to1_mw(3);
    hvdc_pmax_2to1_mw << 20.0, 20.0, 20.0;
    grid.init_hvdc_lines(hvdc_bus1_id, hvdc_bus2_id, hvdc_type1, hvdc_type2, hvdc_loss_factor1, hvdc_loss_factor2, hvdc_vreg1_on, hvdc_vreg2_on, hvdc_vm1_pu, hvdc_vm2_pu, hvdc_q1_setpoint_mvar, hvdc_q2_setpoint_mvar, hvdc_min_q1, hvdc_max_q1, hvdc_min_q2, hvdc_max_q2, hvdc_power_factor1, hvdc_power_factor2, hvdc_converters_mode, hvdc_p_setpoint_mw, hvdc_r_ohm, hvdc_nominal_v_kv, hvdc_droop_enabled, hvdc_droop_p0_mw, hvdc_droop_mw_per_deg, hvdc_pmax_1to2_mw, hvdc_pmax_2to1_mw);

    RealVect storage_p(1);
    storage_p << -5.0;
    RealVect storage_q(1);
    storage_q << -1.0;
    Eigen::VectorXi storage_bus_id(1);
    storage_bus_id << 4;
    grid.init_storages(storage_p, storage_q, storage_bus_id);

    grid.add_gen_slackbus(0, 1.0);

    grid.consider_only_main_component();

    return grid;
}

}  // namespace ls2g_test

#endif  // LS2G_CASE_EXOTIC_ELEMENTS_H
