// Minimal lightsim2grid solver plugin example.
//
// The plugin exposes a single exported entry point (generated by the
// LS2G_PLUGIN_ENTRY macro) that lightsim2grid.load_algorithm_plugin() looks up
// and calls after loading the library, registering "DummyExternal" into the
// AlgorithmRegistry singleton. Doing the registration in an explicitly-called
// entry point (rather than a static constructor firing during dlopen) means a
// registration failure comes back as a catchable Python exception instead of
// aborting the interpreter.
//
// Build (after pip install lightsim2grid):
//   LS2G_CMAKE=$(python -c "import lightsim2grid; print(lightsim2grid.get_cmake_dir())")
//   cmake -S . -B build -DLIGHTSIM2GRID_CMAKE_DIR="$LS2G_CMAKE"
//   cmake --build build
//
// Python usage (from examples/external_algorithm/):
//   import lightsim2grid
//   lightsim2grid.load_algorithm_plugin("build/libdummy_solver.so")
//   grid.change_algorithm("DummyExternal")

#include <AlgorithmRegistry.hpp>
#include <powerflow_algorithm/BaseAlgo.hpp>

// ---------------------------------------------------------------------------
// A trivial AC solver that always "converges" on the first call by returning
// the initial voltage vector unchanged.  Useful as a smoke-test for the
// plugin mechanism; not suitable for real power-flow calculations.
// ---------------------------------------------------------------------------
class DummyExternalAlgo : public ls2g::BaseAlgo {
public:
    DummyExternalAlgo() : ls2g::BaseAlgo(/*is_ac=*/true) {}

    bool compute_pf(
        const Eigen::Ref<const Eigen::SparseMatrix<ls2g::cplx_type> > & /*Ybus*/,
        const Eigen::Ref<const ls2g::CplxVect>                        & V,
        const Eigen::Ref<const ls2g::CplxVect>                        & /*Sbus*/,
        const Eigen::Ref<const ls2g::IntVect>                         & /*slack_ids*/,
        const Eigen::Ref<const ls2g::RealVect>                        & /*slack_weights*/,
        const Eigen::Ref<const ls2g::IntVect>                         & /*pv*/,
        const Eigen::Ref<const ls2g::IntVect>                         & /*pq*/,
        int /*max_iter*/,
        ls2g::real_type /*tol*/) override
    {
        // Store V unchanged and claim convergence.
        V_ = V;
        Va_ = V.array().arg();
        Vm_ = V.array().abs();
        n_  = static_cast<int>(V.size());
        nr_iter_ = 1;
        err_ = ls2g::ErrorType::NoError;
        return true;
    }
};

// ---------------------------------------------------------------------------
// Registration: load_algorithm_plugin() calls ls2g_register_plugin (generated
// by LS2G_PLUGIN_ENTRY) after loading this library.
// ---------------------------------------------------------------------------
static void register_plugin(ls2g::PluginRegistrar& reg) {
    reg.add("DummyExternal",
            []{ return std::unique_ptr<ls2g::BaseAlgo>(new DummyExternalAlgo()); });
}
LS2G_PLUGIN_ENTRY(register_plugin)
