// Copyright (c) 2020-2026, RTE (https://www.rte-france.com)
// See AUTHORS.txt
// This Source Code Form is subject to the terms of the Mozilla Public License, version 2.0.
// If a copy of the Mozilla Public License, version 2.0 was not distributed with this file,
// you can obtain one at http://mozilla.org/MPL/2.0/.
// SPDX-License-Identifier: MPL-2.0
// This file is part of LightSim2grid, LightSim2grid implements a c++ backend targeting the Grid2Op platform.

#include "binding_declarations.hpp"
#include "Solvers.hpp"
#include "ChooseSolver.hpp"
#include "help_fun_msg.hpp"

using namespace ls2g;

void bind_solvers(py::module_& m) {
    py::class_<SparseLUSolver>(m, "SparseLUSolver", DocSolver::SparseLUSolver.c_str())
        .def(py::init<>())
        .def("get_J", &SparseLUSolver::get_J_python, DocSolver::get_J_python.c_str())
        .def("get_Va", &SparseLUSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &SparseLUSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &SparseLUSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &SparseLUSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &SparseLUSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &SparseLUSolver::reset, DocSolver::reset.c_str())
        .def("converged", &SparseLUSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &SparseLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &SparseLUSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &SparseLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<SparseLUSolverSingleSlack>(m, "SparseLUSolverSingleSlack", DocSolver::SparseLUSolverSingleSlack.c_str())
        .def(py::init<>())
        .def("get_J", &SparseLUSolverSingleSlack::get_J_python, DocSolver::get_J_python.c_str())
        .def("get_Va", &SparseLUSolverSingleSlack::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &SparseLUSolverSingleSlack::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &SparseLUSolverSingleSlack::get_V, DocSolver::get_V.c_str())
        .def("get_error", &SparseLUSolverSingleSlack::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &SparseLUSolverSingleSlack::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &SparseLUSolverSingleSlack::reset, DocSolver::reset.c_str())
        .def("converged", &SparseLUSolverSingleSlack::converged, DocSolver::converged.c_str())
        .def("compute_pf", &SparseLUSolverSingleSlack::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &SparseLUSolverSingleSlack::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &SparseLUSolverSingleSlack::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<DCSolver>(m, "DCSolver", DocSolver::DCSolver.c_str())
        .def(py::init<>())
        .def("get_Va", &DCSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &DCSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &DCSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &DCSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &DCSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &DCSolver::reset, DocSolver::reset.c_str())
        .def("converged", &DCSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &DCSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &DCSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &DCSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<FDPF_XB_SparseLUSolver>(m, "FDPF_XB_SparseLUSolver", DocSolver::FDPF_XB_SparseLUSolver.c_str())
        .def(py::init<>())
        .def("get_Va", &FDPF_XB_SparseLUSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &FDPF_XB_SparseLUSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &FDPF_XB_SparseLUSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &FDPF_XB_SparseLUSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &FDPF_XB_SparseLUSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &FDPF_XB_SparseLUSolver::reset, DocSolver::reset.c_str())
        .def("converged", &FDPF_XB_SparseLUSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &FDPF_XB_SparseLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &FDPF_XB_SparseLUSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &FDPF_XB_SparseLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("debug_get_Bp_python", &FDPF_XB_SparseLUSolver::debug_get_Bp_python, DocGridModel::_internal_do_not_use.c_str())
        .def("debug_get_Bpp_python", &FDPF_XB_SparseLUSolver::debug_get_Bpp_python, DocGridModel::_internal_do_not_use.c_str());

    py::class_<FDPF_BX_SparseLUSolver>(m, "FDPF_BX_SparseLUSolver", DocSolver::FDPF_BX_SparseLUSolver.c_str())
        .def(py::init<>())
        .def("get_Va", &FDPF_BX_SparseLUSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &FDPF_BX_SparseLUSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &FDPF_BX_SparseLUSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &FDPF_BX_SparseLUSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &FDPF_BX_SparseLUSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &FDPF_BX_SparseLUSolver::reset, DocSolver::reset.c_str())
        .def("converged", &FDPF_BX_SparseLUSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &FDPF_BX_SparseLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &FDPF_BX_SparseLUSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &FDPF_BX_SparseLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("debug_get_Bp_python", &FDPF_BX_SparseLUSolver::debug_get_Bp_python, DocGridModel::_internal_do_not_use.c_str())
        .def("debug_get_Bpp_python", &FDPF_BX_SparseLUSolver::debug_get_Bpp_python, DocGridModel::_internal_do_not_use.c_str());

#if defined(KLU_SOLVER_AVAILABLE) || defined(_READ_THE_DOCS)
    py::class_<KLUSolver>(m, "KLUSolver", DocSolver::KLUSolver.c_str())
        .def(py::init<>())
        .def("get_J", &KLUSolver::get_J_python, DocSolver::get_J_python.c_str())
        .def("get_Va", &KLUSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &KLUSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &KLUSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &KLUSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &KLUSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &KLUSolver::reset, DocSolver::reset.c_str())
        .def("converged", &KLUSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &KLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &KLUSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &KLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<KLUSolverSingleSlack>(m, "KLUSolverSingleSlack", DocSolver::KLUSolverSingleSlack.c_str())
        .def(py::init<>())
        .def("get_J", &KLUSolverSingleSlack::get_J_python, DocSolver::get_J_python.c_str())
        .def("get_Va", &KLUSolverSingleSlack::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &KLUSolverSingleSlack::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &KLUSolverSingleSlack::get_V, DocSolver::get_V.c_str())
        .def("get_error", &KLUSolverSingleSlack::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &KLUSolverSingleSlack::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &KLUSolverSingleSlack::reset, DocSolver::reset.c_str())
        .def("converged", &KLUSolverSingleSlack::converged, DocSolver::converged.c_str())
        .def("compute_pf", &KLUSolverSingleSlack::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &KLUSolverSingleSlack::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &KLUSolverSingleSlack::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<KLUDCSolver>(m, "KLUDCSolver", DocSolver::KLUDCSolver.c_str())
        .def(py::init<>())
        .def("get_Va", &KLUDCSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &KLUDCSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &KLUDCSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &KLUDCSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &KLUDCSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &KLUDCSolver::reset, DocSolver::reset.c_str())
        .def("converged", &KLUDCSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &KLUDCSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &KLUDCSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &KLUDCSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<FDPF_XB_KLUSolver>(m, "FDPF_XB_KLUSolver", DocSolver::FDPF_XB_KLUSolver.c_str())
        .def(py::init<>())
        .def("get_Va", &FDPF_XB_KLUSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &FDPF_XB_KLUSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &FDPF_XB_KLUSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &FDPF_XB_KLUSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &FDPF_XB_KLUSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &FDPF_XB_KLUSolver::reset, DocSolver::reset.c_str())
        .def("converged", &FDPF_XB_KLUSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &FDPF_XB_KLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &FDPF_XB_KLUSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &FDPF_XB_KLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<FDPF_BX_KLUSolver>(m, "FDPF_BX_KLUSolver", DocSolver::FDPF_BX_KLUSolver.c_str())
        .def(py::init<>())
        .def("get_Va", &FDPF_BX_KLUSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &FDPF_BX_KLUSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &FDPF_BX_KLUSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &FDPF_BX_KLUSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &FDPF_BX_KLUSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &FDPF_BX_KLUSolver::reset, DocSolver::reset.c_str())
        .def("converged", &FDPF_BX_KLUSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &FDPF_BX_KLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &FDPF_BX_KLUSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &FDPF_BX_KLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());
#endif  // KLU_SOLVER_AVAILABLE (or _READ_THE_DOCS)

#if defined(NICSLU_SOLVER_AVAILABLE) || defined(_READ_THE_DOCS)
    py::class_<NICSLUSolver>(m, "NICSLUSolver", DocSolver::NICSLUSolver.c_str())
        .def(py::init<>())
        .def("get_J", &NICSLUSolver::get_J_python, DocSolver::get_J_python.c_str())
        .def("get_Va", &NICSLUSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &NICSLUSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &NICSLUSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &NICSLUSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &NICSLUSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &NICSLUSolver::reset, DocSolver::reset.c_str())
        .def("converged", &NICSLUSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &NICSLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &NICSLUSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &NICSLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<NICSLUSolverSingleSlack>(m, "NICSLUSolverSingleSlack", DocSolver::NICSLUSolverSingleSlack.c_str())
        .def(py::init<>())
        .def("get_J", &NICSLUSolverSingleSlack::get_J_python, DocSolver::get_J_python.c_str())
        .def("get_Va", &NICSLUSolverSingleSlack::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &NICSLUSolverSingleSlack::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &NICSLUSolverSingleSlack::get_V, DocSolver::get_V.c_str())
        .def("get_error", &NICSLUSolverSingleSlack::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &NICSLUSolverSingleSlack::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &NICSLUSolverSingleSlack::reset, DocSolver::reset.c_str())
        .def("converged", &NICSLUSolverSingleSlack::converged, DocSolver::converged.c_str())
        .def("compute_pf", &NICSLUSolverSingleSlack::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &NICSLUSolverSingleSlack::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &NICSLUSolverSingleSlack::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<NICSLUDCSolver>(m, "NICSLUDCSolver", DocSolver::NICSLUDCSolver.c_str())
        .def(py::init<>())
        .def("get_Va", &NICSLUDCSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &NICSLUDCSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &NICSLUDCSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &NICSLUDCSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &NICSLUDCSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &NICSLUDCSolver::reset, DocSolver::reset.c_str())
        .def("converged", &NICSLUDCSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &NICSLUDCSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &NICSLUDCSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &NICSLUDCSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<FDPF_XB_NICSLUSolver>(m, "FDPF_XB_NICSLUSolver", DocSolver::FDPF_XB_NICSLUSolver.c_str())
        .def(py::init<>())
        .def("get_Va", &FDPF_XB_NICSLUSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &FDPF_XB_NICSLUSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &FDPF_XB_NICSLUSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &FDPF_XB_NICSLUSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &FDPF_XB_NICSLUSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &FDPF_XB_NICSLUSolver::reset, DocSolver::reset.c_str())
        .def("converged", &FDPF_XB_NICSLUSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &FDPF_XB_NICSLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &FDPF_XB_NICSLUSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &FDPF_XB_NICSLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<FDPF_BX_NICSLUSolver>(m, "FDPF_BX_NICSLUSolver", DocSolver::FDPF_BX_NICSLUSolver.c_str())
        .def(py::init<>())
        .def("get_Va", &FDPF_BX_NICSLUSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &FDPF_BX_NICSLUSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &FDPF_BX_NICSLUSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &FDPF_BX_NICSLUSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &FDPF_BX_NICSLUSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &FDPF_BX_NICSLUSolver::reset, DocSolver::reset.c_str())
        .def("converged", &FDPF_BX_NICSLUSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &FDPF_BX_NICSLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &FDPF_BX_NICSLUSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &FDPF_BX_NICSLUSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());
#endif  // NICSLU_SOLVER_AVAILABLE (or _READ_THE_DOCS)

#if defined(CKTSO_SOLVER_AVAILABLE) || defined(_READ_THE_DOCS)
    py::class_<CKTSOSolver>(m, "CKTSOSolver", DocSolver::CKTSOSolver.c_str())
        .def(py::init<>())
        .def("get_J", &CKTSOSolver::get_J_python, DocSolver::get_J_python.c_str())
        .def("get_Va", &CKTSOSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &CKTSOSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &CKTSOSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &CKTSOSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &CKTSOSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &CKTSOSolver::reset, DocSolver::reset.c_str())
        .def("converged", &CKTSOSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &CKTSOSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &CKTSOSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &CKTSOSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<CKTSOSolverSingleSlack>(m, "CKTSOSolverSingleSlack", DocSolver::CKTSOSolverSingleSlack.c_str())
        .def(py::init<>())
        .def("get_J", &CKTSOSolverSingleSlack::get_J_python, DocSolver::get_J_python.c_str())
        .def("get_Va", &CKTSOSolverSingleSlack::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &CKTSOSolverSingleSlack::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &CKTSOSolverSingleSlack::get_V, DocSolver::get_V.c_str())
        .def("get_error", &CKTSOSolverSingleSlack::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &CKTSOSolverSingleSlack::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &CKTSOSolverSingleSlack::reset, DocSolver::reset.c_str())
        .def("converged", &CKTSOSolverSingleSlack::converged, DocSolver::converged.c_str())
        .def("compute_pf", &CKTSOSolverSingleSlack::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &CKTSOSolverSingleSlack::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &CKTSOSolverSingleSlack::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<CKTSODCSolver>(m, "CKTSODCSolver", DocSolver::CKTSODCSolver.c_str())
        .def(py::init<>())
        .def("get_Va", &CKTSODCSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &CKTSODCSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &CKTSODCSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &CKTSODCSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &CKTSODCSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &CKTSODCSolver::reset, DocSolver::reset.c_str())
        .def("converged", &CKTSODCSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &CKTSODCSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &CKTSODCSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &CKTSODCSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<FDPF_XB_CKTSOSolver>(m, "FDPF_XB_CKTSOSolver", DocSolver::FDPF_XB_CKTSOSolver.c_str())
        .def(py::init<>())
        .def("get_Va", &FDPF_XB_CKTSOSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &FDPF_XB_CKTSOSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &FDPF_XB_CKTSOSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &FDPF_XB_CKTSOSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &FDPF_XB_CKTSOSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &FDPF_XB_CKTSOSolver::reset, DocSolver::reset.c_str())
        .def("converged", &FDPF_XB_CKTSOSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &FDPF_XB_CKTSOSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &FDPF_XB_CKTSOSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &FDPF_XB_CKTSOSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<FDPF_BX_CKTSOSolver>(m, "FDPF_BX_CKTSOSolver", DocSolver::FDPF_BX_CKTSOSolver.c_str())
        .def(py::init<>())
        .def("get_Va", &FDPF_BX_CKTSOSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &FDPF_BX_CKTSOSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &FDPF_BX_CKTSOSolver::get_V, DocSolver::get_V.c_str())
        .def("get_error", &FDPF_BX_CKTSOSolver::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &FDPF_BX_CKTSOSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &FDPF_BX_CKTSOSolver::reset, DocSolver::reset.c_str())
        .def("converged", &FDPF_BX_CKTSOSolver::converged, DocSolver::converged.c_str())
        .def("compute_pf", &FDPF_BX_CKTSOSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &FDPF_BX_CKTSOSolver::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &FDPF_BX_CKTSOSolver::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());
#endif  // CKTSO_SOLVER_AVAILABLE (or _READ_THE_DOCS)

    py::class_<GaussSeidelAlgo>(m, "GaussSeidelSolver", DocSolver::GaussSeidelSolver.c_str())
        .def(py::init<>())
        .def("get_Va", &GaussSeidelAlgo::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &GaussSeidelAlgo::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &GaussSeidelAlgo::get_V, DocSolver::get_V.c_str())
        .def("get_error", &GaussSeidelAlgo::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &GaussSeidelAlgo::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &GaussSeidelAlgo::reset, DocSolver::reset.c_str())
        .def("converged", &GaussSeidelAlgo::converged, DocSolver::converged.c_str())
        .def("compute_pf", &GaussSeidelAlgo::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &GaussSeidelAlgo::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &GaussSeidelAlgo::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    py::class_<GaussSeidelSynchAlgo>(m, "GaussSeidelSynchSolver", DocSolver::GaussSeidelSynchSolver.c_str())
        .def(py::init<>())
        .def("get_Va", &GaussSeidelSynchAlgo::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &GaussSeidelSynchAlgo::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &GaussSeidelSynchAlgo::get_V, DocSolver::get_V.c_str())
        .def("get_error", &GaussSeidelSynchAlgo::get_error, DocSolver::get_error.c_str())
        .def("get_nb_iter", &GaussSeidelSynchAlgo::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("reset", &GaussSeidelSynchAlgo::reset, DocSolver::reset.c_str())
        .def("converged", &GaussSeidelSynchAlgo::converged, DocSolver::converged.c_str())
        .def("compute_pf", &GaussSeidelSynchAlgo::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str())
        .def("get_timers", &GaussSeidelSynchAlgo::get_timers, DocSolver::get_timers.c_str())
        .def("solve", &GaussSeidelSynchAlgo::compute_pf, py::call_guard<py::gil_scoped_release>(), DocSolver::compute_pf.c_str());

    // Only "const" methods exported so Python cannot modify the internal solver of a gridmodel
    py::class_<ChooseSolver>(m, "AnySolver", DocSolver::AnySolver.c_str())
        .def(py::init<>())
        .def("get_type", &ChooseSolver::get_type, DocSolver::get_type.c_str())
        .def("get_Va", &ChooseSolver::get_Va, DocSolver::get_Va.c_str())
        .def("get_Vm", &ChooseSolver::get_Vm, DocSolver::get_Vm.c_str())
        .def("get_V", &ChooseSolver::get_V, DocSolver::get_V.c_str())
        .def("get_J", &ChooseSolver::get_J_python, DocSolver::chooseSolver_get_J_python.c_str())
        .def("get_error", &ChooseSolver::get_error, DocSolver::get_V.c_str())
        .def("get_nb_iter", &ChooseSolver::get_nb_iter, DocSolver::get_nb_iter.c_str())
        .def("converged", &ChooseSolver::converged, DocSolver::converged.c_str())
        .def("get_computation_time", &ChooseSolver::get_computation_time, DocSolver::get_computation_time.c_str())
        .def("get_timers", &ChooseSolver::get_timers, "TODO")
        .def("get_timers_jacobian", &ChooseSolver::get_timers_jacobian, "TODO")
        .def("get_timers_ptdf_lodf", &ChooseSolver::get_timers_ptdf_lodf, "TODO")
        .def("get_fdpf_xb_lu", &ChooseSolver::get_fdpf_xb_lu, py::return_value_policy::reference, DocGridModel::_internal_do_not_use.c_str())
        .def("get_fdpf_bx_lu", &ChooseSolver::get_fdpf_bx_lu, py::return_value_policy::reference, DocGridModel::_internal_do_not_use.c_str());
}
