version: 2.1

orbs:
    win: circleci/windows@4.1 # The Windows orb give you everything you need to start using the Windows executor.


executors:
    gcc_latest:
        docker:
            - image: gcc:14
    gcc_prev_latest:
        docker:
            - image: gcc:13
    gcc_earliest:
        docker:
            - image: gcc:8
    clang_latest:
        docker:
            - image: silkeh/clang:20
    clang_prev_latest:
        docker:
            - image: silkeh/clang:19
    clang_earliest:
        docker:
            - image: silkeh/clang:11

jobs:
    test_legacy_grid2op:
        executor: gcc_latest
        resource_class: small
        steps:
            - checkout
            - run: cat /etc/os-release
            - run: apt update
            - run: apt install -y python3 python3-dev python3-venv python3-pip git
            - run: 
                  name: Get python version
                  command: 
                      python3 --version
            - run: python3 -m venv venv_test
            - run:
                  name: "Set up virtual environment"
                  command: |
                      source venv_test/bin/activate
                      pip install --upgrade pip setuptools wheel gym "numpy<2" pybind11 scipy
                      pip install "pandapower<3" grid2op==1.0.0
                      git submodule init
                      git submodule update
                      make
                      pip freeze
            - run:
                  name: "Compile and install lightsim2grid"
                  command: |
                      source venv_test/bin/activate
                      CC=gcc python setup.py build
                      python -m pip install -e .
                      pip freeze
            - run:
                name: legacy test (grid2op 1.0.0)
                command: |
                      source venv_test/bin/activate
                      sed -i -e 's/np.int)/np.int32)/g' venv_test/lib/python3.*/site-packages/grid2op/Backend/PandaPowerBackend.py
                      sed -i -e 's/np.bool/np.bool_/g' venv_test/lib/python3.*/site-packages/grid2op/dtypes.py
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            - run:
                name: legacy test (grid2op ~1.1)
                command: |
                      source venv_test/bin/activate
                      pip install "grid2op~=1.1.0"
                      sed -i -e 's/np.int)/np.int32)/g' venv_test/lib/python3.*/site-packages/grid2op/Backend/PandaPowerBackend.py
                      sed -i -e 's/np.bool/np.bool_/g' venv_test/lib/python3.*/site-packages/grid2op/dtypes.py
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            - run:
                name: legacy test (grid2op ~1.2)
                command: |
                      source venv_test/bin/activate
                      pip install "grid2op~=1.2.0"
                      sed -i -e 's/np.int)/np.int32)/g' venv_test/lib/python3.*/site-packages/grid2op/Backend/PandaPowerBackend.py
                      sed -i -e 's/np.bool/np.bool_/g' venv_test/lib/python3.*/site-packages/grid2op/dtypes.py
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            - run:
                name: legacy test (grid2op ~1.3)
                command: |
                      source venv_test/bin/activate
                      pip install "grid2op~=1.3.0"
                      sed -i -e 's/np.int)/np.int32)/g' venv_test/lib/python3.*/site-packages/grid2op/Backend/PandaPowerBackend.py
                      sed -i -e 's/np.bool/np.bool_/g' venv_test/lib/python3.*/site-packages/grid2op/dtypes.py
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            - run:
                name: legacy test (grid2op ~1.4)
                command: |
                      source venv_test/bin/activate
                      pip install "grid2op~=1.4.0"
                      sed -i -e 's/np.int)/np.int32)/g' venv_test/lib/python3.*/site-packages/grid2op/Backend/PandaPowerBackend.py
                      sed -i -e 's/np.bool/np.bool_/g' venv_test/lib/python3.*/site-packages/grid2op/dtypes.py
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            - run:
                name: legacy test (grid2op ~1.5)
                command: |
                      source venv_test/bin/activate
                      pip install "grid2op~=1.5.0"
                      sed -i -e 's/np.int)/np.int32)/g' venv_test/lib/python3.*/site-packages/grid2op/Backend/PandaPowerBackend.py
                      sed -i -e 's/np.bool/np.bool_/g' venv_test/lib/python3.*/site-packages/grid2op/dtypes.py
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            - run:
                name: legacy test (grid2op ~1.6)
                command: |
                      source venv_test/bin/activate
                      pip install "grid2op~=1.6.0"
                      sed -i -e 's/np.int)/np.int32)/g' venv_test/lib/python3.*/site-packages/grid2op/Backend/PandaPowerBackend.py
                      sed -i -e 's/np.bool/np.bool_/g' venv_test/lib/python3.*/site-packages/grid2op/dtypes.py
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            - run:
                name: legacy test (grid2op ~1.7)
                command: |
                      source venv_test/bin/activate
                      pip install "grid2op~=1.7.0"
                      sed -i -e 's/np.int)/np.int32)/g' venv_test/lib/python3.*/site-packages/grid2op/Backend/PandaPowerBackend.py
                      sed -i -e 's/np.bool/np.bool_/g' venv_test/lib/python3.*/site-packages/grid2op/dtypes.py
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            - run:
                name: legacy test (grid2op ~1.8)
                command: |
                      source venv_test/bin/activate
                      pip install "grid2op~=1.8.0"
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            - run:
                name: legacy test (grid2op ~1.9)
                command: |
                      source venv_test/bin/activate
                      pip uninstall gym -y
                      pip install "gymnasium<1"  # issue with OrderedDict otherwise
                      pip install "grid2op~=1.9.0"
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            - run:
                name: legacy test (grid2op ~1.10)
                command: |
                      source venv_test/bin/activate
                      pip install "grid2op~=1.10.0"
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            - run:
                name: legacy test (grid2op 0.9.1.post1 - l2rpn wcci 2020)
                command: |
                      source venv_test/bin/activate
                      pip uninstall gymnasium -y
                      pip install gym
                      pip install grid2op==0.9.1.post1
                      sed -i -e 's/np.int)/np.int32)/g' venv_test/lib/python3.*/site-packages/grid2op/Backend/PandaPowerBackend.py
                      sed -i -e 's/np.bool/np.bool_/g' venv_test/lib/python3.*/site-packages/grid2op/dtypes.py
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            - run:
                name: legacy test (grid2op 1.2.2 - l2rpn neurips 2020)
                command: |
                      source venv_test/bin/activate
                      pip install grid2op==1.2.2
                      sed -i -e 's/np.int)/np.int32)/g' venv_test/lib/python3.*/site-packages/grid2op/Backend/PandaPowerBackend.py
                      sed -i -e 's/np.bool/np.bool_/g' venv_test/lib/python3.*/site-packages/grid2op/dtypes.py
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            # - run:
            #     name: legacy test (grid2op 1.6.3 - l2rpn Icaps 2021)(NOT WORKING WITH PYTHON 3.11)
            #     command: |
            #           source venv_test/bin/activate
            #           pip install grid2op==1.6.3
            #           sed -i -e 's/np.int)/np.int32)/g' venv_test/lib/python3.*/site-packages/grid2op/Backend/PandaPowerBackend.py
            #           sed -i -e 's/np.bool/np.bool_/g' venv_test/lib/python3.*/site-packages/grid2op/dtypes.py
            #           python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            - run:
                name: legacy test (grid2op 1.7.2 - l2rpn wcci 2022)
                command: |
                      source venv_test/bin/activate
                      pip install grid2op==1.7.2
                      sed -i -e 's/np.int)/np.int32)/g' venv_test/lib/python3.*/site-packages/grid2op/Backend/PandaPowerBackend.py
                      sed -i -e 's/np.bool/np.bool_/g' venv_test/lib/python3.*/site-packages/grid2op/dtypes.py
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            - run:
                name: legacy test (grid2op 1.9.0 - l2rpn Delft 2023)
                command: |
                      source venv_test/bin/activate
                      pip uninstall gym -y
                      pip install "gymnasium<1"  # issue with OrderedDict otherwise
                      pip install grid2op==1.9.0
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py
            - run:
                name: legacy test (grid2op 1.9.1 - l2rpn IDF 2023)
                command: |
                      source venv_test/bin/activate
                      pip install grid2op==1.9.1
                      python -m unittest lightsim2grid/tests/test_compat_legacy_grid2op.py

    compile_gcc_prev_latest:
        executor: gcc_prev_latest
        resource_class: small
        steps:
            - checkout
            - run: apt-get update && apt-get install python3-full python3-dev python3-pip python3-virtualenv git -y
            - run: python3 -m virtualenv venv_test
            - run:
                  command: |
                      source venv_test/bin/activate
                      pip install --upgrade pip setuptools wheel
                      pip install -U grid2op
                      pip install -U pybind11
                      git submodule init
                      git submodule update
                      make
                      CC=gcc python setup.py build
                      python -m pip install -U .

    compile_gcc_earliest:
        executor: gcc_earliest
        resource_class: small
        steps:
            - checkout
            - run: apt-get update && apt-get install python3-pip -y
            - run: python3 -m pip install virtualenv
            - run: python3 -m virtualenv venv_test
            - run:
                command: |
                    source venv_test/bin/activate
                    pip install --upgrade pip setuptools wheel
                    pip install -U grid2op
                    pip install -U pybind11
                    git submodule init
                    git submodule update
                    make
                    CC=gcc python setup.py build
                    python -m pip install -U .
    compile_and_test_gcc_latest:
        executor: gcc_latest
        resource_class: medium
        steps:
            - checkout
            - run: apt-get update
            - run: apt install -y python3 python3-dev python3-venv python3-pip git
            - run: 
                  name: Show python version
                  command: 
                      python3 --version
            - run: python3 -m venv venv_test
            - run:
                  name: "Set up virtual environment"
                  command: |
                      source venv_test/bin/activate
                      pip install --upgrade pip setuptools wheel gymnasium "numpy<2" pybind11 scipy
                      git submodule init
                      git submodule update
                      make
                      pip freeze
            - run:
                  name: "Compile and install lightsim2grid"
                  command: |
                      source venv_test/bin/activate
                      CC=gcc python setup.py build
                      CC=gcc python -m pip install -e .
                      pip freeze
            - run:
                name: "Install grid2op from source"
                command: |
                    source venv_test/bin/activate
                    pip install --upgrade pip setuptools wheel
                    git clone https://github.com/Grid2Op/grid2op.git _grid2op
                    pip install -e _grid2op
            - run:
                name: "Show package versions"
                command: |
                    source venv_test/bin/activate
                    pip install pypowsybl
                    pip freeze
            - run:
                name: "make tests"
                command: |
                    source venv_test/bin/activate
                    cd lightsim2grid/tests/
                    python -m unittest discover  -v

    compile_clang_earliest:
        executor: clang_earliest
        resource_class: small
        steps:
            - checkout
            - run: apt-get update && apt-get install python3-pip python3-full git -y
            - run: python3 -m pip install virtualenv
            - run: python3 -m virtualenv venv_test
            - run:
                command: |
                    source venv_test/bin/activate
                    pip install --upgrade pip setuptools wheel
                    pip install -U grid2op
                    pip install -U pybind11
                    git submodule init
                    git submodule update
                    make
                    CC=clang python setup.py build
                    CC=clang python -m pip install -U .

    compile_clang_prev_latest:
        executor: clang_prev_latest
        resource_class: small
        steps:
            - checkout
            - run: apt-get update && apt-get install python3-full python3-dev python3-pip python3-virtualenv git -y
            - run: python3 -m virtualenv venv_test
            - run:
                command: |
                    source venv_test/bin/activate
                    pip install --upgrade pip setuptools wheel
                    pip install -U grid2op
                    pip install -U pybind11
                    git submodule init
                    git submodule update
                    make
                    CC=clang python setup.py build
                    CC=clang python -m pip install -U .

    compile_and_test_clang_latest:
        executor: clang_latest
        resource_class: medium
        steps:
            - checkout
            - run: apt-get update
            - run: apt install -y python3 python3-dev python3-venv python3-pip git
            - run: 
                  name: Show python version
                  command: 
                      python3 --version
            - run: python3 -m venv venv_test
            - run:
                  name: "Set up virtual environment"
                  command: |
                      source venv_test/bin/activate
                      pip install --upgrade pip setuptools wheel 
                      pip install gymnasium "numpy<2" pybind11 scipy
                      git submodule init
                      git submodule update
                      make
                      pip freeze
            - run:
                  name: "Compile and install lightsim2grid"
                  command: |
                      source venv_test/bin/activate
                      CC=clang python setup.py build
                      CC=clang python -m pip install -e .
                      pip freeze
            - run:
                name: "Install grid2op from source"
                command: |
                    source venv_test/bin/activate
                    pip install --upgrade pip setuptools wheel
                    git clone https://github.com/Grid2Op/grid2op.git _grid2op
                    pip install -e _grid2op
            - run:
                name: "Show package versions"
                command: |
                    source venv_test/bin/activate
                    pip install pypowsybl
                    pip freeze
            - run:
                name: "make tests"
                command: |
                    source venv_test/bin/activate
                    cd lightsim2grid/tests/
                    python -m unittest discover  -v
    compile_and_test_windows:
        executor: 
            name: win/default  # executor type
            size: large  # ("medium" "large" "xlarge" "2xlarge")
        steps:
            - checkout
            - run: choco install python --version=3.10  --force -y
            - run: C:\Python310\python --version 
            - run: C:\Python310\python -m pip install --upgrade pip setuptools wheel
            - run: C:\Python310\python -m pip install virtualenv
            - run: C:\Python310\python -m virtualenv venv_test
            - run: 
                name: "Check python  / pip version in venv"
                command: |
                    .\venv_test\Scripts\activate
                    python --version 
                    pip --version
            - run:
                name: "Install grid2op from source"
                command: |
                    .\venv_test\Scripts\activate
                    pip install gymnasium "numpy<2" pybind11 scipy
                    git clone https://github.com/Grid2Op/grid2op.git _grid2op
                    pip install -e _grid2op gymnasium
            - run:
                name: "Install lightsim2grid"
                command: |
                    .\venv_test\Scripts\activate
                    git submodule init
                    git submodule update
                    python setup.py build
                    python -m pip install -e .[test]
                    pip freeze
            - run:
                name: "make tests"
                command: |
                    .\venv_test\Scripts\activate
                    cd lightsim2grid\tests
                    python -m unittest discover -v

workflows:
    version: 2.1
    compile:
        jobs:
          - compile_gcc_earliest
          - compile_gcc_prev_latest
          - compile_clang_earliest
          - compile_clang_prev_latest
          - test_legacy_grid2op
          - compile_and_test_windows
          - compile_and_test_clang_latest
          - compile_and_test_gcc_latest
